version: '2'

services:
  nginx:
    image: nginx
    ports:
        - "80:80"
    links:
        - slim
    volumes:
        - ./nginx/default:/etc/nginx/sites-available/default
        - ./nginx/default:/etc/nginx/sites-enabled/default

        - ./logs/nginx-error.log:/var/log/nginx/error.log
        - ./logs/nginx-access.log:/var/log/nginx/access.log

  slim:
    image: comicrelief/php7-slim:latest
    volumes:
      - ~/Code/Slim-Docker:/var/www/html
    ports:
      - "9001:80"
    depends_on:
      - mysql
    environment:
      APPLICATION_ENV: local

  mysql:
    image: mariadb
    environment:
      MYSQL_ROOT_PASSWORD: admin
      MYSQL_DATABASE: slim

  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    restart: always
    links:
      - mysql
    ports:
      - "8181:80"
    environment:
      PMA_HOST: mysql
      PMA_USER: root
      PMA_PASSWORD: admin
      PMA_ARBITRARY: 1﻿
