version: '2'

services:

  slim-docker:
    image: comicrelief/php7-slim:latest
    volumes:
      - ~/Code/Slim-Docker:/var/www/html
    ports:
      - "9001:80"
    depends_on:
      - mysql
    environment:
      APPLICATION_ENV: local

  mysql:
    image: mariadb
    environment:
      MYSQL_ROOT_PASSWORD: admin
      MYSQL_DATABASE: slim

  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    restart: always
    links:
      - mysql
    ports:
      - "8181:80"
    environment:
      PMA_HOST: mysql
      PMA_USER: root
      PMA_PASSWORD: admin
      PMA_ARBITRARY: 1﻿
